import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ChainId, ThirdwebProvider } from "@thirdweb-dev/react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThirdwebProvider desiredChainId={chainId.mumbai}>
          {children} 
        </ThirdwebProvider>
      </body>
    </html>
  );
}
